keys:
  - &users
    - &software-failsafe age1r8vj8khzcvkz98y9zfep0srwwcmyc34xr2f000fefw4llwm6jsdsx08e2p
    - &yubikey-primary age1xxt8anj4z962kdz9q3hqlqr9cw366c97dy5e7n2jvff3mqjw9e2qffgdp5
    - &yubikey-backup age1fkfwwlq5d782v8slcrqglr9x80ldxkxxwn4mha88dcp6ynta4f9stek96y
  - &hosts
    - &sentinel age1pc9y09smqek88lwqy6kfmz5axy9awj523nlgdv6p48ymvu8xdq2qvmfjft
    - &warden age1hsumcd4kudmx8x9q3wzvjkyfx03djp9kpp9z6pamuyvlpjc329nsmq3qjx

creation_rules:
  - path_regex: ^hosts/common/.*\.ya?ml$
    key_groups:
      - age:
          - *software-failsafe
          - *yubikey-primary
          - *yubikey-backup
          - *sentinel
          - *warden

  - path_regex: ^hosts/atlas/.*\.ya?ml$
    key_groups:
      - age:
          - *software-failsafe
          - *yubikey-primary
          - *yubikey-backup

  - path_regex: ^hosts/warden/.*\.ya?ml$
    key_groups:
      - age:
          - *software-failsafe
          - *yubikey-primary
          - *yubikey-backup
          - *warden

  - path_regex: ^hosts/sentinel/.*\.ya?ml$
    key_groups:
      - age:
          - *software-failsafe
          - *yubikey-primary
          - *yubikey-backup
          - *sentinel
